#!/usr/local/bin/node


let request = require("request");
let url = process.argv[2];

console.log(url);

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
  // Simulate a Document Object Model.
  let { document } = (new JSDOM(body)).window;
  let stories = document.querySelectorAll(".gs-c-promo-heading");
  let news = document.querySelectorAll(".gs-o-bullet__text");
  

  // Print out all of the paragraphs.
  stories.forEach(function(newslink) {
    console.log(newslink.textContent);
  });

    // Print out all of the paragraphs.
  news.forEach(function(newslink) {
    console.log(newslink.textContent);
  });
});