#! /usr/local/bin/node

let fs = require('fs');
let Phrase = require('s33dco-palindrome');

let text = fs.readFileSync("phrases.txt", 'utf-8');

text.split('\n').forEach(function(line){
	let phrase = new Phrase(line);
	if (phrase.palindrome()) {
		// write palindrome to file
		fs.appendFile("palindromes.txt",`palindrome detected: ${line}\n`, (err) => {  
		    if (err) throw err;
		    console.log('palindrome detected and added!');
		});
	}
});